source 'https://rubygems.org'
gem "jekyll", "~> 3.6"
gem 'jekyll-remote-theme', '~> 0.4.3'
gem "jekyll-avatar"
gem "jekyll-coffeescript"
gem "jekyll-default-layout"
gem "jekyll-feed"
gem "jekyll-gist"
gem "jekyll-paginate"
gem "jekyll-mentions"
gem "jekyll-optional-front-matter"
gem "jekyll-readme-index"
gem "jekyll-redirect-from"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-relative-links"
gem "jemoji"
gem "jekyll-titles-from-headings"
gem "jekyll-gitlab-metadata"
gem "kramdown-parser-gfm"